# Generated by Django 4.1 on 2022-09-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_img', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixels',
            name='query',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
